TB specific changes to Safe Inputs
PHACDataHub/tb-safe-inputs pull request #1
Opened 2023-09-18 19:17 UTC by niranjan-ramesh

TB specific enhancements for safe inputs.

- Added validation of excel input
- Test schema used - schema yet to be finalized for PTs

2023-09-19 15:04 UTC, Collinbrown95 commented
@niranjan-ramesh I think in the spirit of "1 PR = 1 feature", the only thing I'd like to flesh out in this PR is a high-level overview of what the user experience for data validation looks like. We can iterate on this, of course, but I think getting a minimum implementation of editable tables + tooltips is a good starting point.

If you're up for it, I propose we implement some of the UX changes discussed in the review thread, then merge this into the `main` branch and tackle next steps in a separate branch.

Great work, this is an awesome feature! :)

2023-09-19 15:24 UTC, niranjan-ramesh commented
@Collinbrown95 Thank you for checking the branch. That sounds great. We can get started on these changes.

2023-09-20 19:06 UTC, Collinbrown95 requested changes
Finishing the review.

2023-09-22 18:18 UTC, niranjan-ramesh commented on ui/src/components/PaginatedTable.tsx
@Collinbrown95 I have pushed changes implementing (1) and (2) and have made some re-organization including (3). 

<img width="1123" alt="image" src="https://github.com/PHACDataHub/tb-safe-inputs/assets/19886426/39f63a7b-d9e7-4399-a007-26489c1ef5f1">

<img width="682" alt="image" src="https://github.com/PHACDataHub/tb-safe-inputs/assets/19886426/210cf9f5-342f-4bc6-811b-1af1d8cd6a59">

EditableCell is a component with the data, error label and callbacks to modify the original data and re-run validation. 

I would love to get your feedback on the changes.

2023-09-25 16:56 UTC, Collinbrown95 approved these changes
Looks good to me!

2023-09-25 16:56 UTC, Collinbrown95 commented on ui/src/utils/errorUtils.ts
> +export const constructErrorMessage = (error: ErrorObject):string => {
As discussed offline, we'll incorporate this refactor into a separate PR later on.

2023-09-25 16:58 UTC, merged