DRAFT: Sample report from fake generated file for BC province
PHACDataHub/tb-safe-inputs pull request #3
Opened 2023-09-27 16:48 UTC by niranjan-ramesh

Draft Pull Request for reviews and comments:

- Fake generated CaseUploading file for BC province.
- Data Transformations using pysqldf and pandas based on convenience of TB team

2023-09-27 18:39 UTC, Collinbrown95 requested changes
I've requested a few small changes, but on the whole this is looking great! Great work!

2023-09-27 18:39 UTC, Collinbrown95 commented on analytics-environment/analyze-synthetic-data.ipynb
> +    "\""
Can you define this with a multi-line string in python? E.g.

```python
SQL_QUERY = """
client_id_phac AS RegisterCaseNumber,
    classification_date AS DiagnosisDate,
    classification_year AS Survey_Year,
    CASE
        WHEN lower(classification) = 'clinical' THEN 2
        WHEN lower(classification) = 'confirmed' THEN 1
    END AS CaseCriteria,
...
"""
```

Reason is to avoid the need to include the `\` after every line to continue the string.

2023-09-27 18:39 UTC, Collinbrown95 commented on analytics-environment/analyze-synthetic-data.ipynb
> +    "pysqldf = lambda q: sqldf(q, globals())"
What are your thoughts on using [duckdb](https://github.com/duckdb/duckdb) instead of [pysqldf](https://github.com/airtoxin/pysqldf)? I suggest this because it looks like pysqldf is no longer maintained, while duckdb is actively maintained.

I've not played with it personally, but it looks like duckdb has a [Python API](https://duckdb.org/docs/api/python/overview.html) that allows a very similar syntax to what you're trying to achieve.

2023-09-27 18:39 UTC, Collinbrown95 commented on analytics-environment/BC.xlsx
What do you think about having a `test/` folder in `analytics-environment/` to store this file, then `.gitignore` `*.xlsx` files outside of the test folder in general? You might be able to do something like 

```.gitignore
# .gitignore file

# Ignore everything matching `*.xlsx` from the top of the repo,
# except for anything matching analytics-environment/tests/*.xlsx
*.xlsx
!analytics-environment/tests/*.xlsx
```

This one is OK since it's a small amount of synthetic data, and is explicitly a test input for our programs. However, in general, we don't want to store Excel workbooks in the git repository.

2023-09-27 18:39 UTC, Collinbrown95 commented on analytics-environment/environments/analytics/environment.yml
Small recommendation: when you're generating your `environment.yml` manifest, you can do the following:

```bash
conda env export --no-builds | grep -v "^prefix: " > environment.yml
```

The `--no-builds` part excludes build information after each version, and the `grep -v "^prefix:"` part matches everything except the `prefix:...` line.

The resulting `environment.yml` file doesn't specify any build information, and also doesn't specify a filesystem location for the conda environment.

2023-09-27 18:39 UTC, Collinbrown95 commented on analytics-environment/environments/synthetic-data-generation/environment.yml
Why two separate conda environments? Is it possible to consolidate all of the dependencies into a single conda environment?

Since the users will be very new to the Python ecosystem, we could significantly simplify their experience by having all of their dependencies installed in a single environment :)

2023-09-28 14:50 UTC, niranjan-ramesh commented on analytics-environment/analyze-synthetic-data.ipynb
> +    "\""
Removed the `\` and made the strings multi-line.

2023-09-28 14:51 UTC, niranjan-ramesh commented on analytics-environment/analyze-synthetic-data.ipynb
> +    "pysqldf = lambda q: sqldf(q, globals())"
Totally for it :) Removed `pysqldf` and have setup up the environment with `duckdb`.

2023-09-28 14:53 UTC, niranjan-ramesh commented on analytics-environment/environments/analytics/environment.yml
Single conda environment file with the build information removed :) Thank you for the command.

2023-09-28 20:48 UTC, merged

2023-09-28 20:48 UTC, Collinbrown95 commented
LGTM!